# -*- coding: utf-8 -*-
"""ab_pipline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KblnD0igXxgtMWiEVFVBqH8KJe3tDnlJ
"""

import json

kaggle_dict = {
    "username": "chintu's work",
    "key": "KGAT_20567e8d06942818eda68d64f5e2ddcf"
}

with open("kaggle.json", "w") as f:
    json.dump(kaggle_dict, f)

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!pip install kaggle

!kaggle datasets download -d mkechinov/ecommerce-behavior-data-from-multi-category-store

!unzip ecommerce-behavior-data-from-multi-category-store.zip

import dask.dataframe as dd

df = dd.read_csv("2019-Oct.csv")
df.head()

df=df[['event_time','event_type','user_id','product_id']]

df=df.sample(frac=0.2,random_state=42).compute()

df.info()

len(df)

df.isnull().sum()

df.duplicated().sum()

df.nunique()

df.reset_index(drop=True,inplace=True)

df.head()

import pandas as pd
import numpy as np
df['variant']=np.random.choice(['A','B'],size=len(df))

funnel = df.groupby(['variant', 'event_type'])['user_id'].nunique().reset_index()
print(funnel)

total_users = df.groupby('variant')['user_id'].nunique()

purchases = df[df['event_type']=='purchase'].groupby('variant')['user_id'].nunique()

conversion = (purchases / total_users).reset_index()
conversion.columns = ['variant', 'conversion_rate']

print(conversion)

from statsmodels.stats.proportion import proportions_ztest

A_users = total_users['A']
B_users = total_users['B']

A_conv = purchases['A']
B_conv = purchases['B']

count = [A_conv, B_conv]
nobs = [A_users, B_users]

stat, pval = proportions_ztest(count, nobs)

print("p-value:", pval)

import sqlite3

conn = sqlite3.connect("ab_project.db")

# store conversion
conversion.to_sql("conversion_results", conn, if_exists="replace", index=False)

funnel.to_sql("funnel_results", conn, if_exists="replace", index=False)

